jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { 
                          url 'https://gitlab.com/swinburne-dxp/swinburne-core.git' 
                        }
                        branch '*/task/jenkins-develop'
                        extensions {}
                    }
                  }
              }
          }
      }